apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-ncio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-ncio
    app.kubernetes.io/part-of: test-app-866
  name: nodejs-no-dockerfile-ncio
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-ncio
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-ncio
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-866/nodejs-no-dockerfile-ncio@sha256:ea87f9ceae60ec713c1b2defba29d0334a85c946834e132ac242f5631ae9f2d6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
