apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-hhea
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-hhea
    app.kubernetes.io/part-of: test-app-866
  name: retrodep-hhea
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-hhea
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-hhea
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-866/retrodep-hhea@sha256:44123f022ebf75f0a496e71fdec90e8da2144550e36be496e5fa0b140aa5db30
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
