apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-6zx5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-6zx5
    app.kubernetes.io/part-of: test-app-866
  name: pip-e2e-test-6zx5
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-6zx5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-6zx5
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-866/pip-e2e-test-6zx5@sha256:e9f0c7794fe9a68f47cb1200a0af3fb151d89d5d637c9f5d9c55ec1ec32df4bf
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
