apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-6koz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-use-latest-parent-image-6koz
    app.kubernetes.io/part-of: test-app-866
  name: e2e-tests-use-latest-parent-image-6koz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-6koz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-use-latest-parent-image-6koz
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-866/e2e-tests-use-latest-parent-image-6koz@sha256:93ca98dc245c6e7bd2717b0669d7b31a701924440da75cfe9930c79a3f0014eb
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
