apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-apun
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-apun
    app.kubernetes.io/part-of: test-app-866
  name: e2e-tests-parent-image-with-digest-only-apun
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-apun
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-apun
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-866/e2e-tests-parent-image-with-digest-only-apun@sha256:1c2f2bfe04d4939b98f1bafd5aafa77c24a3a08ccb73482f6db21577a749b8fa
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
