apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-cmfo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-cmfo
    app.kubernetes.io/part-of: test-app-866
  name: maven-hello-world-cmfo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-cmfo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-cmfo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-866/maven-hello-world-cmfo@sha256:1002971ae88ce46c106c60340b08c0301a5f0d67e189d6181ed02e265193ffa6
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
